const suggestedAccounts = [
    {
        id: 3,
        first_name: "Đào Lê",
        last_name: "Phương Hoa",
        full_name: "Đào Lê Phương Hoa",
        nickname: "hoaahanassii",
        avatar: "https://files.fullstack.edu.vn/f8-tiktok/users/2/627394cb56d66.jpg",
        bio: "✨ 1998 ✨\nVietnam 🇻🇳\nĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !",
        tick: true,
        followings_count: 1,
        followers_count: 87,
        likes_count: 1000,
        website_url: "https://fullstack.edu.vn/",
        facebook_url: "",
        youtube_url: "",
        twitter_url: "",
        instagram_url: "",
        created_at: "2022-05-05 23:10:05",
        updated_at: "2022-05-05 23:11:39"
    },
    {
        id: 23,
        first_name: "Nguyễn Minh",
        last_name: "Tâm",
        full_name: "Nguyễn Minh Tâm",
        nickname: "leducanhvu2305",
        avatar: "https://files.fullstack.edu.vn/f8-tiktok/users/5677/64898e74a309a.jpg",
        bio: "✨ 2003 ✨\nVietnam 🇻🇳\nĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !",
        tick: false,
        followings_count: 1,
        followers_count: 4,
        likes_count: 8,
        website_url: "https://minhtam.edu.vn",
        facebook_url: "",
        youtube_url: "",
        twitter_url: "",
        instagram_url: "",
        created_at: "2023-06-11 14:01:59",
        updated_at: "2024-01-17 13:44:48"
    },
    {
        id: 19,
        first_name: "Huỳnh",
        last_name: "Khoa",
        full_name: "Huỳnh Khoa",
        nickname: "bhuynhcongkhoa",
        avatar: "https://files.fullstack.edu.vn/f8-tiktok/users/192/631560ee94071.png",
        bio: "mày/tao",
        tick: true,
        followings_count: 9,
        followers_count: 1,
        likes_count: 5,
        website_url: "https://fullstack.edu.vn/huynhkhoa66",
        facebook_url: "",
        youtube_url: "",
        twitter_url: "",
        instagram_url: "",
        created_at: "2022-09-05 09:27:58",
        updated_at: "2023-12-05 17:45:03"
    }
]

const followedAccounts = [
    {
        id: 6080,
        first_name: "Lê Thị",
        last_name: "Ngọc Huyền",
        full_name: "Lê Thị Ngọc Huyền",
        nickname: "anhthien632001",
        avatar: "https://files.fullstack.edu.vn/f8-tiktok/users/6080/65f2c13149558.jpg",
        bio: "✨ 1999✨\r\nVietnam 🇻🇳\r\nXINH Gái!!",
        tick: true,
        followings_count: 27,
        followers_count: 1,
        likes_count: 0,
        website_url: "https://fullstack.edu.vn/",
        facebook_url: "",
        youtube_url: "",
        twitter_url: "",
        instagram_url: "",
        created_at: "2023-08-21 15:09:16",
        updated_at: "2024-03-14 16:19:46"
    },
    {
        id: 6924,
        first_name: "Lê Thị",
        last_name: "Hồng Nhung",
        full_name: "Lê Thị Hồng Nhung",
        nickname: "lethihongnhung2021n",
        avatar: "https://images.pexels.com/photos/414612/pexels-photo-414612.jpeg?auto=compress&cs=tinysrgb&w=600",
        bio: "FE Web Developer",
        tick: true,
        followings_count: 11,
        followers_count: 9813,
        likes_count: 102343,
        website_url: "https://fullstack.edu.vn/",
        facebook_url: "",
        youtube_url: "",
        twitter_url: "",
        instagram_url: "",
        created_at: "2024-08-24 07:24:41",
        updated_at: "2024-09-07 23:11:13"
    },
    {
        id: 5030,
        first_name: "Trần Thị",
        last_name: "Vỹ",
        full_name: "Trần Thị Vỹ",
        nickname: "tranthivy0402",
        avatar: "https://images.pexels.com/photos/1386604/pexels-photo-1386604.jpeg?auto=compress&cs=tinysrgb&w=600",
        bio: "",
        tick: false,
        followings_count: 1,
        followers_count: 199,
        likes_count: 872,
        website_url: "",
        facebook_url: "",
        youtube_url: "",
        twitter_url: "",
        instagram_url: "",
        created_at: "2023-02-24 22:24:42",
        updated_at: "2023-02-24 22:24:45"
    },
]

export { suggestedAccounts, followedAccounts };